# Generated by Django 6.0.1 on 2026-01-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='contentes',
            new_name='content',
        ),
    ]
